"use client"
import "@workspace/ui/styles/globals.css"
import { Geist, Geist_Mono } from "next/font/google"
import { useEffect } from "react"
import { setTokenFn } from "@/services/api"
import { TooltipProvider } from "@workspace/ui/components/tooltip"

import { Button } from "@workspace/ui/components/button"
import { ClerkProvider } from "@clerk/nextjs"
import StoreProvider from "@/store/provider"
import useSyncUser from "@/hooks/syncUser"
import { useAuth } from "@clerk/nextjs"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const SyncUserWrapper = ({ children }) => {
  useSyncUser()
  return <>{children}</>
}

const ClerkTokenProvider = () => {
  const { getToken } = useAuth()
  useEffect(() => {
    setTokenFn(getToken)
  }, [getToken])

  return null
}

const Logger = ({ children }) => {
  const { getToken, user, isSignedUp, isLoading } = useAuth()
  useEffect(() => {
    console.log("Hello from the logger!")
    console.log("User:", user)

    const fetchData = async () => {
      console.log("Token:", getToken())
      const token = await getToken()
      const rawRes = await fetch("http://localhost:5000/api/user/sync", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: "example@text",
        }),
      })
      const res = await rawRes.json()
      console.log("Response from API:", res)
    }
    fetchData()
  }, [isLoading, isSignedUp])

  return <>{children}</>
}

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <ClerkProvider>
            <StoreProvider>
              <SyncUserWrapper>
                <ClerkTokenProvider />
                {children}
              </SyncUserWrapper>
            </StoreProvider>
          </ClerkProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}
